import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const readmePath = path.join(__dirname, '..', 'README.md');

if (fs.existsSync(readmePath)) {
  let content = fs.readFileSync(readmePath, 'utf8');
  // Replace the hover text injected by readme-aura
  content = content.replace(/"Generated by readme-aura"/g, '"Generated by profile-aura"');
  fs.writeFileSync(readmePath, content, 'utf8');
  console.log('✅ Fixed README hover text branding.');
}
