import fs from 'fs';
import path from 'path';
import { Logger } from '../../utils/logger.js';
import { ProfileAuraConfig } from '../../types/config.js';
import { ThemeRegistry } from '../../themes/registry.js';
import { Command } from 'commander';

export function registerWrapCommand(program: Command) {
  program
    .command('wrap-snake <snakeSvgPath>')
    .description('Wraps the generated snake game SVG in the active Profile Aura theme container')
    .option('-c, --config <path>', 'Path to configuration file', 'profile-aura.config.json')
    .action(wrapSnakeAction);
}

export async function wrapSnakeAction(snakeSvgPath: string, options: any) {
  try {
    const configPath = path.resolve(process.cwd(), options.config || 'profile-aura.config.json');
    if (!fs.existsSync(configPath)) {
      Logger.error(`Configuration file not found at ${configPath}`);
      process.exit(1);
    }

    const config: ProfileAuraConfig = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    const theme = ThemeRegistry.getTheme(config.theme || 'void-dark');

    const absoluteSvgPath = path.resolve(process.cwd(), snakeSvgPath);
    if (!fs.existsSync(absoluteSvgPath)) {
      Logger.error(`Snake SVG not found at ${absoluteSvgPath}. Ensure the snk action ran successfully.`);
      process.exit(1);
    }

    // Read the raw animated SVG generated by Platane/snk
    const rawSnakeSvg = fs.readFileSync(absoluteSvgPath, 'utf8');

    // Snake SVG comes with its own width/height on the <svg> tag. We want to extract its inner content and attributes.
    const match = rawSnakeSvg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i);
    if (!match) {
      Logger.error(`Invalid SVG format in ${absoluteSvgPath}`);
      process.exit(1);
    }
    let innerContent = match[1];

    // Build the beautiful wrapper container
    const width = 800;
    const height = 300; 
    const bg = theme.colors.cardBackground || '#000000';
    const border = theme.colors.border || '#333333';
    const accent = theme.colors.accentPrimary || '#A855F7';
    const textMuted = theme.colors.textMuted || '#888888';

    // Make text contrast correctly within snake if it has classes (the snk SVG uses css for dots)
    // We'll leave snk's inner CSS intact, it will render correctly.

    const wrappedSvg = `
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <!-- Background & Border -->
  <rect x="0" y="0" width="${width}" height="${height}" rx="12" fill="${bg}" stroke="${border}" stroke-width="1"/>
  
  <!-- Pulsing Glow (Theme matched) -->
  <defs>
    <radialGradient id="glow" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="${accent}" stop-opacity="0.15" />
      <stop offset="100%" stop-color="transparent" stop-opacity="0" />
    </radialGradient>
  </defs>
  <rect x="150" y="-150" width="300" height="300" fill="url(#glow)" />

  <!-- Section Title -->
  <text x="28" y="34" font-family="system-ui, -apple-system, sans-serif" font-size="11" font-weight="800" fill="${accent}" letter-spacing="2">
    // CONTRIBUTIONS GRAPH
  </text>
  <text x="210" y="34" font-family="system-ui, -apple-system, sans-serif" font-size="9" fill="${textMuted}">
    (Powered by GitHub Actions &amp; profile-aura)
  </text>

  <!-- Nested Snake Game -->
  <g transform="translate(10, 60)">
    ${innerContent}
  </g>
</svg>
    `.trim();

    fs.writeFileSync(absoluteSvgPath, wrappedSvg, 'utf8');

    Logger.success(`Successfully wrapped snake game at ${snakeSvgPath} with '${config.theme}' theme!`);
  } catch (err: any) {
    Logger.error(`Failed to wrap snake game: ${err.message}`);
    process.exit(1);
  }
}
